#!/bin/bash

# Translate input environment variables
DEPLOY_SERVER="$INPUT_DEPLOY_SERVER"
DEPLOY_USERNAME="$INPUT_DEPLOY_USERNAME"
DEPLOY_PASSWORD="$INPUT_DEPLOY_PASSWORD"
DEPLOY_ROOT_DIR="$INPUT_DEPLOY_ROOT_DIR"
ENCRYPTED_DEPLOY_KEY_CYPHER_KEY="$INPUT_ENCRYPTED_DEPLOY_KEY_CYPHER_KEY"
ENCRYPTED_DEPLOY_KEY_CYPHER_IV="$INPUT_ENCRYPTED_DEPLOY_KEY_CYPHER_IV"
ENCRYPTED_DEPLOY_KEY_PATH="$INPUT_ENCRYPTED_DEPLOY_KEY_PATH"
APP_PATH="$INPUT_PATH"

cat "/github/workspace/$APP_PATH/.gitignore"

docker images

docker images -q "$GITHUB_REPOSITORY" 2> /dev/null
