#!/bin/bash

# Translate input environment variables
DEPLOY_SERVER="$INPUT_DEPLOY_SERVER"
DEPLOY_USERNAME="$INPUT_DEPLOY_USERNAME"
DEPLOY_PASSWORD="$INPUT_DEPLOY_PASSWORD"
ENCRYPTED_DEPLOY_KEY_CYPHER_KEY="$INPUT_ENCRYPTED_DEPLOY_KEY_CYPHER_KEY"
ENCRYPTED_DEPLOY_KEY_CYPHER_IV="$INPUT_ENCRYPTED_DEPLOY_KEY_CYPHER_IV"
ENCRYPTED_DEPLOY_KEY_PATH="$INPUT_ENCRYPTED_DEPLOY_KEY_PATH"

cat /github/workspace/README.md
