#!/bin/bash

echo "DEPLOY_SERVER: $INPUT_DEPLOY_SERVER"
echo "DEPLOY_USERNAME: $INPUT_DEPLOY_USERNAME"
echo "DEPLOY_PASSWORD: $INPUT_DEPLOY_PASSWORD"
echo "ENCRYPTED_DEPLOY_KEY_CYPHER_KEY: $INPUT_ENCRYPTED_DEPLOY_KEY_CYPHER_KEY"
echo "ENCRYPTED_DEPLOY_KEY_CYPHER_IV: $INPUT_ENCRYPTED_DEPLOY_KEY_CYPHER_IV"
echo "ENCRYPTED_DEPLOY_KEY_PATH: $INPUT_ENCRYPTED_DEPLOY_KEY_PATH"

cat /github/workspace/README.md
